"""change the table users, adding four columns and remove column 'name'

Revision ID: 1d5ece6de752
Revises: 581bc17aeee3
Create Date: 2016-10-17 12:51:22.565065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5ece6de752'
down_revision = '581bc17aeee3'
branch_labels = None
depends_on = None


def upgrade():
    # commands auto generated by Alembic - please adjust! #
    op.add_column(
        'users', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column(
        'users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column(
        'users', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column(
        'users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.drop_column('users', 'name')
    # end Alembic commands #


def downgrade():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('users', sa.Column(
        'name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'email')
    op.drop_column('users', 'admin')
    # end Alembic commands #
